# Generated by Django 3.2.3 on 2021-06-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='作品标题', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='内容', max_length=500),
        ),
    ]
